vhdl work $ROOT_DIR/source/rtl/basic_functions.vhd
vhdl work $ROOT_DIR/source/rtl/final_cpa.vhd
vhdl work $ROOT_DIR/source/rtl/sdn_gen.vhd
vhdl work $ROOT_DIR/source/rtl/pp_rdcn.vhd
vhdl work $ROOT_DIR/source/rtl/pp_gen_rdcn.vhd
vhdl work $ROOT_DIR/source/rtl/multiplier_top.vhd
vhdl work $ROOT_DIR/source/rtl/three2two.vhd
vhdl work $ROOT_DIR/source/rtl/auto_multiplier.vhd
vhdl work $ROOT_DIR/source/rtl/cpa.vhd
vhdl work $ROOT_DIR/source/rtl/dot_operator.vhd
vhdl work $ROOT_DIR/source/rtl/auto_cpa.vhd
vhdl work $ROOT_DIR/source/rtl/cpa_wrapper.vhd
