$ROOT_DIR/source/rtl/basic_functions.vhd
$ROOT_DIR/source/rtl/final_cpa.vhd
$ROOT_DIR/source/rtl/sdn_gen.vhd
$ROOT_DIR/source/rtl/pp_rdcn.vhd
$ROOT_DIR/source/rtl/pp_gen_rdcn.vhd
$ROOT_DIR/source/rtl/multiplier_top.vhd
$ROOT_DIR/source/rtl/three2two.vhd
$ROOT_DIR/source/rtl/cpa.vhd
$ROOT_DIR/source/rtl/dot_operator.vhd
$ROOT_DIR/source/tb/multiplier_top_tb.vhd
